version: '3'
services:
  web:
    image:
    environment:
    - NAME=
    - USER=
    - PASSWORD=
    - HOST=
    - PORTDB=
    network_mode: "host"
    entrypoint:
      - sh
      - -c
      - "python3 manage.py migrate &&
         python3 manage.py runserver"
