version: '3'
services:
  web:
    image:
    environment:
    - NAME=
    - USER=
    - PASSWORD=
    - HOST=
    - PORTDB=
    network_mode: "host"
    command: python3 manage.py migrate
    command: python3 manage.py runserver
    volumes:
     - .:/app
